development:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: action_cable_project_development

test:
  adapter: async

production:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: action_cable_project_production
